name: CI

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/kevinwright1-dev/ci-cd-pipeline-demo

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: sudo docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .

      - name: Push image
        run: |
          sudo docker push $IMAGE_NAME:${{ github.sha }}
          sudo docker push $IMAGE_NAME:latest